-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--#######################################################################################

-- AUTOGENERATED HYPR CONFIG.

-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,

-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.

--#######################################################################################

--
-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

--

-- See https://wiki.hyprland.org/Configuring/Monitors/

-- Monitor Config

-- Laptop Screen

hl.monitor({
	output = "eDP-1",
	mode = "preferred",
	position = "auto",
	scale = 1.6,
})

-- External screens two 27"

hl.monitor({
	output = "DP-5",
	mode = "preferred",
	position = "auto",
	scale = 1.25,
})

hl.monitor({
	output = "DP-7",
	mode = "preferred",
	position = "auto-right",
	scale = 1.25,
})

-- Home Monitor

hl.monitor({
	output = "desc:WAM TYPE-C",
	mode = "preferred",
	position = "auto-right",
	scale = 1,
})

-- Work monitor inverted 32"

hl.monitor({
	output = "desc:Dell Inc.DELL U3223QE FLP7FH3",
	mode = "preferred",
	position = "auto-left",
	scale = 1.25,
})

-- Mirror laptop to the TV

hl.monitor({
	output = "HDMI-A-1",
	mode = "preferred",
	position = "auto",
	scale = 1,
	mirror = "eDP-1",
})

-- All other monitors

hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = "auto",
})

-- Fallback in case of error

hl.monitor({
	output = "FALLBACK",
	mode = "1920x1080@60",
	position = "auto",
	scale = 1,
})

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

-- Set Home Folder

local HOME = "/home/jesper"

-- Startup apps for Hyprland

-- Startup apps

--exec-once = outlook-for-linux

--exec-once = teams-for-linux

-- Some default env vars.

hl.env("EDITOR", "nvim")

hl.env("XCURSOR_SIZE", 24)

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("GBM_BACKEND", "nvidia-drm")

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.env("XDG_SCREENSHOTS_DIR", "/home/jesper/Pictures/Screenshots")

-- Less hazzel with electron apps in wayland (works for some, see hyprland webpage for more info)

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

-- For less lag on screen in wayland

hl.env("KWIN_DRM_USE_MODIFIERS", 0)

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.config({
	input = {
		kb_layout = "se,us",
		kb_options = "caps:swapescape",
		follow_mouse = 1,
		touchpad = {
			natural_scroll = false,
		},
		sensitivity = 0,
		-- -1.0 - 1.0, 0 means no modification.
	},
})

hl.config({
	cursor = {
		no_hardware_cursors = false,
		enable_hyprcursor = true,
	},
})

hl.config({
	general = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		gaps_in = 5,
		gaps_out = 20,
		border_size = 2,
		layout = "dwindle",
		-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
		col = {
			active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
			inactive_border = "rgba(595959aa)",
		},
	},
})

hl.config({
	decoration = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		rounding = 10,
		blur = {
			enabled = false,
			size = 3,
			passes = 1,
		},
	},
})

hl.config({
	animations = {
		enabled = true,
		-- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
	},
})
hl.curve("myBezier", {
	type = "bezier",
	points = { { 0.05, 0.9 }, { 0.1, 1.05 } },
})
hl.animation({ leaf = "windows", enabled = true, speed = 7, bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 7, bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 7, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 6, bezier = "default" })

hl.config({
	dwindle = {
		-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
		preserve_split = true,
		-- you probably want this
	},
})

hl.config({
	scrolling = {
		direction = "right",
		column_width = 1.0,
		follow_focus = true,
	},
})

hl.gesture({
	["fingers"] = 3,
	["direction"] = "horizontal",
	["action"] = "workspace",
})

hl.config({
	misc = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		force_default_wallpaper = 0,
		-- Set to 0 to disable the anime mascot wallpapers
	},
})

hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})

hl.workspace_rule({
	workspace = 1,
	monitor = "eDP-1",
})

hl.workspace_rule({
	workspace = 2,
	monitor = "eDP-1",
})

hl.workspace_rule({
	workspace = 3,
	monitor = "DP-5",
})

hl.workspace_rule({
	workspace = 4,
	monitor = "DP-5",
	layout = "scrolling",
	--layoutopt = "direction:right",
})

hl.workspace_rule({
	workspace = 5,
	monitor = "DP-5",
})

hl.workspace_rule({
	workspace = 8,
	monitor = "DP-7",
})

hl.workspace_rule({
	workspace = 9,
	monitor = "DP-7",
})

hl.workspace_rule({
	workspace = 10,
	monitor = "DP-7",
	layout = "scrolling",
	--layoutopt = "direction:right",
})

--workspace = 10, monitor:DP-7, layoutopt:orientation:right

-- Example windowrule v1

-- windowrule = float, ^(kitty)$

-- Example windowrule v2

-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

--## Window Rules

hl.window_rule({
	name = "zenWorkspace",
	match = {
		class = "zen",
	},
	workspace = 3,
})

hl.window_rule({
	name = "outlookWorkspace",
	match = {
		class = "outlook-for-linux",
	},
	workspace = 10,
})

hl.window_rule({
	name = "slackWorkspace",
	match = {
		class = "Slack",
	},
	workspace = 10,
})

hl.window_rule({
	name = "teamsWorkspace",
	match = {
		class = "teams-for-linux",
	},
	workspace = 10,
})

--### 1Password Rules

hl.window_rule({
	name = "1passwordWorkspace",
	match = {
		title = "(1Password)",
	},
	float = true,
	size = { "(monitor_w*0.7)", "(monitor_h*0.7)" },
	center = true,
})

hl.window_rule({
	name = "quickAccessWorkspace",
	match = {
		title = "^(Quick Access)(.*)$",
	},
	center = true,
	stay_focused = true,
})

--### Global Protect Rules

hl.window_rule({
	name = "gpWorkspace",
	match = {
		title = "(GlobalProtect)",
	},
	stay_focused = true,
	float = true,
	size = { "(monitor_w*0.3)", "(monitor_h*0.3)" },
	center = true,
	monitor = "current",
})

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

local mainMod = "SUPER"

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd("ghostty"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("nautilus"))

hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("/home/jesper/.nix-profile/bin/rofi -show drun"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

--bind = $mainMod,        T, togglesplit, # dwindle

hl.bind(mainMod .. " + " .. "W", hl.dsp.group.toggle())

-- dwindle

-- Custom Binds

hl.bind(
	"Print",
	hl.dsp.exec_cmd("/home/jesper/.nix-profile/bin/hyprshot -m window -o/home/jesper/Pictures/Screenshots")
)

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "X", hl.dsp.exec_cmd("hyprlock"))

hl.bind(
	mainMod .. " + " .. "SHIFT" .. " + " .. "S",
	hl.dsp.exec_cmd("/home/jesper/.nix-profile/bin/hyprshot -z -m region --clipboard-only")
)

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.exec_cmd("wlogout --protocol layer-shell -b 5"))

hl.bind(
	mainMod .. " + " .. "SHIFT" .. " + " .. "V",
	hl.dsp.exec_cmd("cliphist list | rofi -dmenu | cliphist decode | wl-copy")
)

hl.bind(
	mainMod .. " + " .. "SHIFT" .. " + " .. "C",
	hl.dsp.exec_cmd(
		"/home/jesper/.nix-profile/bin/rofi -show calc -modi calc -no-show-match -no-sort -calc-command \"echo -n '{result}' | wl-copy\""
	)
)

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "N", hl.dsp.exec_cmd("swaync-client -t -sw"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "P", hl.dsp.exec_cmd("1password --quick-access"))

-- Duck Sound Bind

hl.bind("XF86Launch8", hl.dsp.exec_cmd("pw-play /home/jesper/git/fedora-home-manager/sounds/duck-quack-1.mp3"))

hl.bind("XF86Launch9", hl.dsp.exec_cmd("pw-play /home/jesper/git/fedora-home-manager/sounds/duck-quack-2.mp3"))

hl.bind("code:197", hl.dsp.exec_cmd("pw-play /home/jesper/git/fedora-home-manager/sounds/duck-quack-3.mp3"))

-- Brightness controlls

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -d intel_backlight set +5%"))

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -d intel_backlight set 5%-"))

-- Temp binding

hl.bind(
	mainMod .. " + " .. "SHIFT" .. " + " .. "B",
	hl.dsp.exec_cmd("/home/jesper/git/fedora-home-manager/modules/waybar/launch.sh")
)

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

-- Move active, switch with next window

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "h", hl.dsp.window.swap({ direction = "left" }))

-- TODO: manual review (unknown dispatcher: moveactive)
-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "h", hl.dsp.moveactive("-50 0"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "l", hl.dsp.window.swap({ direction = "right" }))

-- TODO: manual review (unknown dispatcher: moveactive)
-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "l", hl.dsp.moveactive("50 0"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "k", hl.dsp.window.swap({ direction = "up" }))

-- TODO: manual review (unknown dispatcher: moveactive)
-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "k", hl.dsp.moveactive("0 -50"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "j", hl.dsp.window.swap({ direction = "down" }))

-- TODO: manual review (unknown dispatcher: moveactive)
-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "j", hl.dsp.moveactive("0 50"))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Switch to extended workspaces with mainMod + CTRL + [0-9]

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 1, hl.dsp.focus({ workspace = 11 }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 2, hl.dsp.focus({ workspace = 12 }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 3, hl.dsp.focus({ workspace = 13 }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 4, hl.dsp.focus({ workspace = 14 }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 5, hl.dsp.focus({ workspace = 15 }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 6, hl.dsp.focus({ workspace = 16 }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 7, hl.dsp.focus({ workspace = 17 }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 8, hl.dsp.focus({ workspace = 18 }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 9, hl.dsp.focus({ workspace = 19 }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. 0, hl.dsp.focus({ workspace = 20 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Switch to extended workspaces with mainMod + CTRL + [0-9]

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 11 }))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 12 }))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 13 }))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 14 }))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 15 }))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 16 }))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 17 }))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 18 }))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 19 }))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 20 }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "Space", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Space", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("swww-daemon --format xrgb")
	hl.exec_cmd("waybar & swaync")
	hl.exec_cmd("blueman-applet")
	hl.exec_cmd("waypaper --restore")
	hl.exec_cmd("wl-paste --watch cliphist store")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("lxpolkit")
	hl.exec_cmd("/usr/lib/kdeconnectd")
	hl.exec_cmd("kdeconnect-indicator")
	hl.exec_cmd("systemctl --user import-environment QT_QPA_PLATFORMTHEME WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("/usr/libexec/hyprpolkitagent &")
	hl.exec_cmd("/home/jesper/.cargo/bin/hyprland-per-window-layout")
	hl.exec_cmd("zen-browser")
	hl.exec_cmd("flatpak run com.slack.Slack")
	hl.exec_cmd("/home/jesper/git/appimages/Obsidian-1.9.12.AppImage")
end)
